-- MySQL Script generated by MySQL Workbench
-- Thu Sep 27 15:33:16 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sport
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sport` ;

-- -----------------------------------------------------
-- Schema sport
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sport` DEFAULT CHARACTER SET utf8 ;
USE `sport` ;

-- -----------------------------------------------------
-- Table `sport`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sport`.`user` ;

CREATE TABLE IF NOT EXISTS `sport`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `firstName` VARCHAR(255) NULL DEFAULT NULL,
  `lastName` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sport`.`card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sport`.`card` ;

CREATE TABLE IF NOT EXISTS `sport`.`card` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `expiration_date` VARCHAR(255) NULL DEFAULT NULL,
  `issue_date` VARCHAR(255) NULL DEFAULT NULL,
  `pin_code` INT(11) NULL DEFAULT NULL,
  `fk_card_user` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKkodws6imvfbun4xal8rbc5tom` (`fk_card_user` ASC),
  CONSTRAINT `FKkodws6imvfbun4xal8rbc5tom`
    FOREIGN KEY (`fk_card_user`)
    REFERENCES `sport`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sport`.`contacttype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sport`.`contacttype` ;

CREATE TABLE IF NOT EXISTS `sport`.`contacttype` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sport`.`filial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sport`.`filial` ;

CREATE TABLE IF NOT EXISTS `sport`.`filial` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `building` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `country` VARCHAR(255) NULL DEFAULT NULL,
  `indexCity` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `street` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sport`.`contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sport`.`contact` ;

CREATE TABLE IF NOT EXISTS `sport`.`contact` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `data` VARCHAR(255) NULL DEFAULT NULL,
  `fk_contact_type` INT(11) NULL DEFAULT NULL,
  `fk_filial` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK72btlvjikx402msv1sy1gx9w3` (`fk_contact_type` ASC),
  INDEX `FK9d5wpcbeooir85dceiv94fg97` (`fk_filial` ASC),
  CONSTRAINT `FK72btlvjikx402msv1sy1gx9w3`
    FOREIGN KEY (`fk_contact_type`)
    REFERENCES `sport`.`contacttype` (`id`),
  CONSTRAINT `FK9d5wpcbeooir85dceiv94fg97`
    FOREIGN KEY (`fk_filial`)
    REFERENCES `sport`.`filial` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sport`.`news`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sport`.`news` ;

CREATE TABLE IF NOT EXISTS `sport`.`news` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `date` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `imageURL` VARCHAR(255) NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
