-- MySQL Script generated by MySQL Workbench
-- Mon Oct 22 16:42:09 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sport
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sport
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sport` DEFAULT CHARACTER SET utf8 ;
USE `sport` ;

-- -----------------------------------------------------
-- Table `sport`.`administrator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sport`.`administrator` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `admin_hash` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `login` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sport`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sport`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `first_name` VARCHAR(255) NULL DEFAULT NULL,
  `last_name` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(255) NULL DEFAULT NULL,
  `user_hash` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sport`.`card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sport`.`card` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `expiration_date` VARCHAR(255) NULL DEFAULT NULL,
  `issue_date` VARCHAR(255) NULL DEFAULT NULL,
  `pin_code` INT(11) NULL DEFAULT NULL,
  `user_fk` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKhoc7pihw5o9vjxu96ieu3d7in` (`user_fk` ASC),
  CONSTRAINT `FKhoc7pihw5o9vjxu96ieu3d7in`
    FOREIGN KEY (`user_fk`)
    REFERENCES `sport`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sport`.`filiation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sport`.`filiation` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `building` VARCHAR(255) NULL DEFAULT NULL,
  `caption` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `country` VARCHAR(255) NULL DEFAULT NULL,
  `index_city` VARCHAR(255) NULL DEFAULT NULL,
  `street` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sport`.`contact_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sport`.`contact_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sport`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sport`.`contact` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `data` VARCHAR(255) NULL DEFAULT NULL,
  `contact_type_fk` INT(11) NULL DEFAULT NULL,
  `filiation_fk` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKsawgyggxoqvjsarwgq2itc5ib` (`contact_type_fk` ASC),
  INDEX `FK56j6o6apd7c84ly4doikpaqqb` (`filiation_fk` ASC),
  CONSTRAINT `FK56j6o6apd7c84ly4doikpaqqb`
    FOREIGN KEY (`filiation_fk`)
    REFERENCES `sport`.`filiation` (`id`),
  CONSTRAINT `FKsawgyggxoqvjsarwgq2itc5ib`
    FOREIGN KEY (`contact_type_fk`)
    REFERENCES `sport`.`contact_type` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sport`.`day`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sport`.`day` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sport`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sport`.`news` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `date` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `image_url` TEXT NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sport`.`training_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sport`.`training_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `description` TEXT NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sport`.`training`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sport`.`training` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `time` TIME NULL DEFAULT NULL,
  `day_fk` INT(11) NULL DEFAULT NULL,
  `filiation_fk` INT(11) NULL DEFAULT NULL,
  `training_type_fk` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKk24pr5qi8r5uvhwyqyxkhrmgj` (`day_fk` ASC),
  INDEX `FKlmyo5tlbatqexl6kodufl78vn` (`filiation_fk` ASC),
  INDEX `FK1gwaxs30uhygu8r7qu4jrv4m1` (`training_type_fk` ASC),
  CONSTRAINT `FK1gwaxs30uhygu8r7qu4jrv4m1`
    FOREIGN KEY (`training_type_fk`)
    REFERENCES `sport`.`training_type` (`id`),
  CONSTRAINT `FKk24pr5qi8r5uvhwyqyxkhrmgj`
    FOREIGN KEY (`day_fk`)
    REFERENCES `sport`.`day` (`id`),
  CONSTRAINT `FKlmyo5tlbatqexl6kodufl78vn`
    FOREIGN KEY (`filiation_fk`)
    REFERENCES `sport`.`filiation` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
